### ISSUE TITLE
dies on unicode strings (e.g. ☃)

### ISSUE THREAD

**Issue by garu** [CaballerosTeam/Sort-Naturally-XS#2] opened 2018-05-11 12:57 UTC
Hi! Thank you for writing Sort::Naturally::XS, it looks really great.

I'm having trouble using it though because right now it die()s whenever it tries to sort strings with UTF-8 characters. Here's the simplest example I could come up with to reproduce it:

> `perl -MSort::Naturally::XS -E 'my @l = ( qq(\x{2603}), q(abc) ); say join q(, ) => nsort(@l)'`
Wide character in subroutine entry at -e line 1.

Ideally, Sort::Naturally::XS would use the [Unicode Collation Algorithm](https://www.unicode.org/reports/tr10/) to compare unicode characters/strings, but even just giving it some sort of fixed sort value (instead of raising an exception) and documenting this should be enough I guess.

Hope this helps! And thanks again for writing and maintaining Sort::Naturally::XS!

**Comment by CaballerosTeam** [comment] 2018-05-16 20:38
Hello, regarding to Unicode Collation Algorithm - there is a fork of this module based on ICU library - https://github.com/CaballerosTeam/Sort-Naturally-ICU. Anyway, it has exactly the same issue, so I'll work on it. Thanks.

**Comment by garu** [comment] 2018-05-16 23:57
Thanks for the quick reply! Hope to see a new release soon \o/

**Comment by CaballerosTeam** [comment] 2018-06-12 19:30
Well, the issue is fixed in 968540305d10f276c707390fced5d8667bdec1a8. Now `nsort`, `ncmp`, `sorted` treat wide characters without exception. There is only one special case - locale aware sorting. If you'd like to sort a list according to a locale, you have to make sure the list does not contain wide characters or explicitly encode them.

Let me know if you have any questions.

Thanks.

**Comment by CaballerosTeam** [comment] 2018-06-17 16:31
https://github.com/CaballerosTeam/Sort-Naturally-XS/releases/tag/v0.7.9

**Closed by CaballerosTeam** 2018-06-17 16:31 UTC
Labels: bug
